[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501
maxUploadSize = 200
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false
